#ifndef ALGORITHM_CONFIG_H
#define ALGORITHM_CONFIG_H

/*	========================== 雷达参数 =============================	*/
#define PARAM_RANGE_RES                 75            //距离分辨率：75厘米

/*	=================================================================	*/


/*  ========================== 算法参数 =============================	*/
#define PARAM_MAX_MOTION_RANGE          1050
#define PARAM_MAX_MOTIONLESS_RANGE      1050
#define PARAM_MOTION_MAX                (PARAM_MAX_MOTION_RANGE/PARAM_RANGE_RES)
#define PARAM_MOTIONLESS_MAX            (PARAM_MAX_MOTIONLESS_RANGE/PARAM_RANGE_RES)

#define PARAM_MOTION_SENSITIBITY_RANG0    (20)//1~100
#define PARAM_MOTION_SENSITIBITY_RANG1    (20)
#define PARAM_MOTION_SENSITIBITY_RANG2    (20)
#define PARAM_MOTION_SENSITIBITY_RANG3    (20)
#define PARAM_MOTION_SENSITIBITY_RANG4    (20)
#define PARAM_MOTION_SENSITIBITY_RANG5    (20)
#define PARAM_MOTION_SENSITIBITY_RANG6    (20)
#define PARAM_MOTION_SENSITIBITY_RANG7    (20)
#define PARAM_MOTION_SENSITIBITY_RANG8    (20)
#define PARAM_MOTION_SENSITIBITY_RANG9    (20)
#define PARAM_MOTION_SENSITIBITY_RANG10   (20)
#define PARAM_MOTION_SENSITIBITY_RANG11   (20)
#define PARAM_MOTION_SENSITIBITY_RANG12   (20)
#define PARAM_MOTION_SENSITIBITY_RANG13   (20)


#define PARAM_MOTIONLESS_SENSITIBITY_RANG0    (25)//1~100
#define PARAM_MOTIONLESS_SENSITIBITY_RANG1    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG2    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG3    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG4    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG5    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG6    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG7    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG8    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG9    (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG10   (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG11   (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG12   (25)
#define PARAM_MOTIONLESS_SENSITIBITY_RANG13   (25)


#define PARAM_OFF_TIME                  5       // s


/*	=================================================================	*/

#endif
